version: '3'

services:
  hreact:
    image: node:latest
    container_name: 'unrweb-mui'
    hostname: 'unrweb-mui'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ./src:/var/www/html
    networks:
      - dumynet
networks:
  dumynet:
    external: true

